/** @type {import('tailwindcss').Config} */
const { heroui } = require("@heroui/react");

export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/styles/**/*.{css,less,scss,less,css}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
    "./src/pages/**/*.{js,ts,jsx,tsx}",
    "./node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "rgb(var(--color-primary-500))",
          50: "rgb(var(--color-primary-50))",
          100: "rgb(var(--color-primary-100))",
          200: "rgb(var(--color-primary-200))",
          300: "rgb(var(--color-primary-300))",
          400: "rgb(var(--color-primary-400))",
          500: "rgb(var(--color-primary-500))",
          600: "rgb(var(--color-primary-600))",
          700: "rgb(var(--color-primary-700))",
          800: "rgb(var(--color-primary-800))",
          900: "rgb(var(--color-primary-900))",
          950: "rgb(var(--color-primary-950))",
        },
        neutral: {
          DEFAULT: "rgb(var(--color-neutral-500))",
          50: "rgb(var(--color-neutral-50))",
          100: "rgb(var(--color-neutral-100))",
          200: "rgb(var(--color-neutral-200))",
          300: "rgb(var(--color-neutral-300))",
          400: "rgb(var(--color-neutral-400))",
          500: "rgb(var(--color-neutral-500))",
          600: "rgb(var(--color-neutral-600))",
          700: "rgb(var(--color-neutral-700))",
          800: "rgb(var(--color-neutral-800))",
          900: "rgb(var(--color-neutral-900))",
          950: "rgb(var(--color-neutral-950))",
        },
        error: {
          DEFAULT: "rgb(var(--color-error-500))",
          50: "rgb(var(--color-error-50))",
          100: "rgb(var(--color-error-100))",
          200: "rgb(var(--color-error-200))",
          300: "rgb(var(--color-error-300))",
          400: "rgb(var(--color-error-400))",
          500: "rgb(var(--color-error-500))",
          600: "rgb(var(--color-error-600))",
          700: "rgb(var(--color-error-700))",
          800: "rgb(var(--color-error-800))",
          900: "rgb(var(--color-error-900))",
        },
        warning: {
          DEFAULT: "rgb(var(--color-warning-500))",
          50: "rgb(var(--color-warning-50))",
          100: "rgb(var(--color-warning-100))",
          200: "rgb(var(--color-warning-200))",
          300: "rgb(var(--color-warning-300))",
          400: "rgb(var(--color-warning-400))",
          500: "rgb(var(--color-warning-500))",
          600: "rgb(var(--color-warning-600))",
          700: "rgb(var(--color-warning-700))",
          800: "rgb(var(--color-warning-800))",
          900: "rgb(var(--color-warning-900))",
        },
        success: {
          DEFAULT: "rgb(var(--color-success-500))",
          50: "rgb(var(--color-success-50))",
          100: "rgb(var(--color-success-100))",
          200: "rgb(var(--color-success-200))",
          300: "rgb(var(--color-success-300))",
          400: "rgb(var(--color-success-400))",
          500: "rgb(var(--color-success-500))",
          600: "rgb(var(--color-success-600))",
          700: "rgb(var(--color-success-700))",
          800: "rgb(var(--color-success-800))",
          900: "rgb(var(--color-success-900))",
        },
        "brand-primary": "rgb(var(--color-brand-primary))",
        "default-font": "rgb(var(--color-default-font))",
        "subtext-color": "rgb(var(--color-subtext-color))",
        "neutral-border": "rgb(var(--color-neutral-border))",
        white: "rgb(var(--color-white))",
        black: "rgb(var(--color-black))",
        "default-background": "rgb(var(--color-default-background))",
        "dark-background": "rgb(var(--color-dark-background))",
      },
      fontSize: {
        caption: [
          "12px",
          { lineHeight: "16px", fontWeight: "400", letterSpacing: "0em" },
        ],
        "caption-bold": [
          "12px",
          { lineHeight: "16px", fontWeight: "500", letterSpacing: "0em" },
        ],
        body: [
          "14px",
          { lineHeight: "20px", fontWeight: "400", letterSpacing: "0em" },
        ],
        "body-bold": [
          "14px",
          { lineHeight: "20px", fontWeight: "500", letterSpacing: "0em" },
        ],
        "heading-3": [
          "16px",
          { lineHeight: "20px", fontWeight: "500", letterSpacing: "0em" },
        ],
        "heading-2": [
          "20px",
          { lineHeight: "24px", fontWeight: "500", letterSpacing: "0em" },
        ],
        "heading-1": [
          "30px",
          { lineHeight: "36px", fontWeight: "500", letterSpacing: "0em" },
        ],
        "monospace-body": [
          "14px",
          { lineHeight: "20px", fontWeight: "400", letterSpacing: "0em" },
        ],
      },
      fontFamily: {
        caption: "Inter",
        "caption-bold": "Inter",
        body: "Inter",
        "body-bold": "Inter",
        "heading-3": "Inter",
        "heading-2": "Inter",
        "heading-1": "Inter",
        "monospace-body": "monospace",
      },
      boxShadow: {
        sm: "0px 1px 2px 0px rgba(0, 0, 0, 0.05)",
        default: "0px 1px 2px 0px rgba(0, 0, 0, 0.05)",
        md: "0px 4px 16px -2px rgba(0, 0, 0, 0.08), 0px 2px 4px -1px rgba(0, 0, 0, 0.08)",
        lg: "0px 12px 32px -4px rgba(0, 0, 0, 0.08), 0px 4px 8px -2px rgba(0, 0, 0, 0.08)",
        overlay:
          "0px 12px 32px -4px rgba(0, 0, 0, 0.08), 0px 4px 8px -2px rgba(0, 0, 0, 0.08)",
      },
      borderRadius: {
        sm: "2px",
        md: "4px",
        DEFAULT: "4px",
        lg: "8px",
        full: "9999px",
      },
      container: {
        padding: {
          DEFAULT: "16px",
          sm: "calc((100vw + 16px - 640px) / 2)",
          md: "calc((100vw + 16px - 768px) / 2)",
          lg: "calc((100vw + 16px - 1024px) / 2)",
          xl: "calc((100vw + 16px - 1280px) / 2)",
          "2xl": "calc((100vw + 16px - 1536px) / 2)",
        },
      },
      spacing: {
        112: "28rem",
        144: "36rem",
        192: "48rem",
        256: "64rem",
        320: "80rem",
      },
      screens: {
        mobile: {
          max: "767px",
        },
      },
    },
  },
  plugins: [
    heroui({
      prefix: "heroui",
      addCommonColors: true,
    }),
  ],
};
